version: '3'

services:
  app:
    container_name: food-equeue-api
    build: .
    ports:
      - '3010:3000'
    volumes:
      - sqlite_data:/usr/src/app/db
      # - .:/usr/src/app
      # - /usr/src/app/node_modules
    environment:
      NODE_ENV: production
volumes:
  sqlite_data: