version: '3'

services:
  app:
    container_name: food-equeue-api
    build: .
    ports:
      - '3002:3000'
    # volumes:
      # - .:/usr/src/app
      # - /usr/src/app/node_modules
    environment:
      NODE_ENV: production
